class ProductData {
  static const List<Map<String, dynamic>> sliderData = [
    {
      "sliderId": 901,
      "sliderName": "Vegitable",
      "message": "From Our Garden",
      "image":
          "https://media.istockphoto.com/id/1403036306/photo/wide-horizontal-seamless-pattern-of-vegetables-and-fruits-on-green.jpg?s=612x612&w=0&k=20&c=guEffnjHdPMN0Gm9T9ikixAozv42_5521WH5CpCh84Y=",
    },
    {
      "sliderId": 902,
      "sliderName": "Tomato",
      "message": "Farmers Vagitable",
      "image":
          "https://cdn.prod.website-files.com/62297f6fa9b6c86667bb54eb/6291b72916f0c71a5873894d_hero-image-2.jpg",
    },
    {
      "sliderId": 903,
      "sliderName": "Vegitable2",
      "message": "Happy Farmer",
      "image":
          "https://www.shutterstock.com/image-photo/smiling-woman-farmer-just-harvested-260nw-2416160553.jpg",
    },
  ];

  static const List<Map<String, dynamic>> productData = [
    {
      "productId": 1001,
      "category": {"cId": 2001, "categoryName": "Fruits"},
      "brand": {"bId": 3001, "brandName": "none"},
      "remark": {"rId": 4001, "remarkName": "Best Selling"},
      "productName": "Banana",
      "description": "Yellow Banana",
      "quantity": "1",
      "quantity_unit": "pc",
      "price": 4.99,
      "discount": 0.00,
      "ratings": 4.5,
      "available": true,
      "stockAmount": 100,
      "image":
          "https://cdn.pixabay.com/photo/2017/06/27/22/21/banana-2449019_640.jpg",
    },
    {
      "productId": 1002,
      "category": {"cId": 2002, "categoryName": "Vegetables"},
      "brand": {"bId": 3002, "brandName": "Green Harvest"},
      "remark": {"rId": 4002, "remarkName": "Organic"},
      "productName": "Carrot",
      "description": "Fresh organic carrots",
      "quantity": "500",
      "quantity_unit": "g",
      "price": 2.49,
      "discount": 0.00,
      "ratings": 4.7,
      "available": true,
      "stockAmount": 75,
      "image":
          "https://media.istockphoto.com/id/1388403435/photo/fresh-carrots-isolated-on-white-background.jpg?s=612x612&w=0&k=20&c=XmrTb_nASc7d-4zVKUz0leeTT4fibDzWi_GpIun0Tlc=",
    },
    {
      "productId": 1003,
      "category": {"cId": 2003, "categoryName": "Dairy"},
      "brand": {"bId": 3003, "brandName": "MilkLife"},
      "remark": {"rId": 4003, "remarkName": "New Arrival"},
      "productName": "Whole Milk",
      "description": "Fresh whole milk 1L",
      "quantity": "1",
      "quantity_unit": "L",
      "price": 3.29,
      "discount": 0.10,
      "ratings": 4.3,
      "available": true,
      "stockAmount": 50,
      "image":
          "https://www.shutterstock.com/image-photo/pouring-fresh-milk-into-glass-260nw-2309221837.jpg",
    },
    {
      "productId": 1004,
      "category": {"cId": 2004, "categoryName": "Bakery"},
      "brand": {"bId": 3004, "brandName": "Golden Grain"},
      "remark": {"rId": 4001, "remarkName": "Best Selling"},
      "productName": "Whole Wheat Bread",
      "description": "Fresh whole wheat bread",
      "quantity": "1",
      "quantity_unit": "loaf",
      "price": 2.99,
      "discount": .3,
      "ratings": 4.6,
      "available": true,
      "stockAmount": 40,
      "image": "",
    },
    {
      "productId": 1005,
      "category": {"cId": 2005, "categoryName": "Meat"},
      "brand": {"bId": 3005, "brandName": "Prime Cut"},
      "remark": {"rId": 4004, "remarkName": "Premium"},
      "productName": "Chicken Breast",
      "description": "Boneless chicken breast",
      "quantity": "1",
      "quantity_unit": "kg",
      "price": 8.99,
      "discount": 0.00,
      "ratings": 4.8,
      "available": true,
      "stockAmount": 30,
      "image":
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkxvQ-oDutafNImCAxnn1j1WWxosv0SzeHeg&s",
    },
    {
      "productId": 1006,
      "category": {"cId": 2001, "categoryName": "Fruits"},
      "brand": {"bId": 3001, "brandName": "none"},
      "remark": {"rId": 4005, "remarkName": "Seasonal"},
      "productName": "Strawberries",
      "description": "Fresh juicy strawberries",
      "quantity": "250",
      "quantity_unit": "g",
      "price": 3.99,
      "discount": 0.00,
      "ratings": 4.4,
      "available": true,
      "stockAmount": 60,
      "image":
          "https://media.istockphoto.com/id/1143163513/photo/fresh-organic-red-ripe-strawberry-fruit-background-closeup.jpg?s=612x612&w=0&k=20&c=2zga2WiDUpQSpQ4wpZYyeBXTlWe3aSm1D679rO0FBPg=",
    },
    {
      "productId": 1007,
      "category": {"cId": 2006, "categoryName": "Beverages"},
      "brand": {"bId": 3006, "brandName": "AquaPure"},
      "remark": {"rId": 4006, "remarkName": "Essential"},
      "productName": "Mineral Water",
      "description": "Natural mineral water",
      "quantity": "1",
      "quantity_unit": "L",
      "price": 0.99,
      "discount": 0.00,
      "ratings": 4.2,
      "available": true,
      "stockAmount": 200,
      "image":
          "https://media.istockphoto.com/id/454273399/photo/pouring-water-from-bottle-into-glass-on-blue-background.jpg?s=612x612&w=0&k=20&c=0SLUO53_48thzcpFVLrEiF9Yb8jTbKmO0acUpWsC3yg=",
    },
    {
      "productId": 1008,
      "category": {"cId": 2007, "categoryName": "Snacks"},
      "brand": {"bId": 3007, "brandName": "Crunchy"},
      "remark": {"rId": 4007, "remarkName": "Family Pack"},
      "productName": "Potato Chips",
      "description": "Classic salted chips",
      "quantity": "150",
      "quantity_unit": "g",
      "price": 2.49,
      "discount": 0.00,
      "ratings": 4.0,
      "available": true,
      "stockAmount": 80,
      "image":
          "https://m.media-amazon.com/images/I/514xVUdk6ML._AC_UF1000,1000_QL80_.jpg",
    },
    {
      "productId": 1009,
      "category": {"cId": 2008, "categoryName": "Frozen Foods"},
      "brand": {"bId": 3008, "brandName": "Frosty"},
      "remark": {"rId": 4008, "remarkName": "Easy Meal"},
      "productName": "Mixed Vegetables",
      "description": "Frozen mixed vegetables",
      "quantity": "1",
      "quantity_unit": "kg",
      "price": 3.49,
      "discount": 0.00,
      "ratings": 4.1,
      "available": true,
      "stockAmount": 45,
      "image":
          "https://media.istockphoto.com/id/1342679798/photo/mix-of-different-frozen-vegetables-on-wooden-board-on-the-table-frozen-food.jpg?s=612x612&w=0&k=20&c=TdVUZJA0FIrI2dl7fAo7kTM1QhfsWzX7rW161ham0To=",
    },
    {
      "productId": 1010,
      "category": {"cId": 2009, "categoryName": "Canned Goods"},
      "brand": {"bId": 3009, "brandName": "Pantry"},
      "remark": {"rId": 4009, "remarkName": "Long Shelf Life"},
      "productName": "Tomato Soup",
      "description": "Creamy tomato soup",
      "quantity": "400",
      "quantity_unit": "g",
      "price": 1.99,
      "discount": 0.00,
      "ratings": 4.3,
      "available": true,
      "stockAmount": 65,
      "image":
          "https://www.rawblend.com.au/wp-content/uploads/2021/06/Creamy-Tomato-Soup-1920x1080-1.jpg",
    },
    {
      "productId": 1011,
      "category": {"cId": 2002, "categoryName": "Vegetables"},
      "brand": {"bId": 3002, "brandName": "Green Harvest"},
      "remark": {"rId": 4002, "remarkName": "Organic"},
      "productName": "Broccoli",
      "description": "Fresh organic broccoli",
      "quantity": "1",
      "quantity_unit": "pc",
      "price": 1.99,
      "discount": 0.00,
      "ratings": 4.5,
      "available": true,
      "stockAmount": 55,
      "image":
          "https://media.istockphoto.com/id/915331918/photo/broccoli-in-an-old-metal-colander.jpg?s=612x612&w=0&k=20&c=5Bm0dL_Xth6Jvx97CC0zZ5_8PLQlNThpuOaesk_Ex9Y=",
    },
    {
      "productId": 1012,
      "category": {"cId": 2003, "categoryName": "Dairy"},
      "brand": {"bId": 3010, "brandName": "Cheesy"},
      "remark": {"rId": 4001, "remarkName": "Best Selling"},
      "productName": "Cheddar Cheese",
      "description": "Mild cheddar cheese block",
      "quantity": "200",
      "quantity_unit": "g",
      "price": 3.49,
      "discount": 0.15,
      "ratings": 4.7,
      "available": true,
      "stockAmount": 40,
      "image": "",
    },
    {
      "productId": 1013,
      "category": {"cId": 2010, "categoryName": "Personal Care"},
      "brand": {"bId": 3011, "brandName": "CleanLife"},
      "remark": {"rId": 4010, "remarkName": "Eco-Friendly"},
      "productName": "Hand Soap",
      "description": "Natural hand soap",
      "quantity": "250",
      "quantity_unit": "ml",
      "price": 2.99,
      "discount": 0.00,
      "ratings": 4.6,
      "available": true,
      "stockAmount": 70,
      "image":
          "https://www.shutterstock.com/image-photo/cosmetics-bottles-natural-handmade-soap-260nw-144549866.jpg",
    },
    {
      "productId": 1014,
      "category": {"cId": 2011, "categoryName": "Cleaning Supplies"},
      "brand": {"bId": 3012, "brandName": "Sparkle"},
      "remark": {"rId": 4011, "remarkName": "Value Pack"},
      "productName": "Dishwashing Liquid",
      "description": "Lemon scented dish soap",
      "quantity": "500",
      "quantity_unit": "ml",
      "price": 1.79,
      "discount": 0.00,
      "ratings": 4.4,
      "available": true,
      "stockAmount": 90,
      "image":
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTgTgN6Hyzh9mU9a2K0P0bvWRWNJadMHCvlZw&s",
    },
    {
      "productId": 1015,
      "category": {"cId": 2001, "categoryName": "Fruits"},
      "brand": {"bId": 3001, "brandName": "none"},
      "remark": {"rId": 4005, "remarkName": "Seasonal"},
      "productName": "Blueberries",
      "description": "Fresh blueberries",
      "quantity": "125",
      "quantity_unit": "g",
      "price": 3.49,
      "discount": 0.00,
      "ratings": 4.3,
      "available": true,
      "stockAmount": 35,
      "image":
          "https://www.thefruitcompany.com/cdn/shop/products/mountain-blueberries_grande.jpg?v=1720715612",
    },
    {
      "productId": 1016,
      "category": {"cId": 2004, "categoryName": "Bakery"},
      "brand": {"bId": 3013, "brandName": "SweetTreat"},
      "remark": {"rId": 4003, "remarkName": "New Arrival"},
      "productName": "Chocolate Croissant",
      "description": "Buttery croissant with chocolate",
      "quantity": "1",
      "quantity_unit": "pc",
      "price": 1.99,
      "discount": 0.00,
      "ratings": 4.8,
      "available": true,
      "stockAmount": 25,
      "image":
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaQ7ZI7xbuTBcF8xij-5eii_9kYZGh1n9pfw&s",
    },
    {
      "productId": 1017,
      "category": {"cId": 2006, "categoryName": "Beverages"},
      "brand": {"bId": 3014, "brandName": "Juicy"},
      "remark": {"rId": 4012, "remarkName": "No Added Sugar"},
      "productName": "Orange Juice",
      "description": "100% pure orange juice",
      "quantity": "1",
      "quantity_unit": "L",
      "price": 3.49,
      "discount": 0.00,
      "ratings": 4.5,
      "available": true,
      "stockAmount": 40,
      "image":
          "https://images.unsplash.com/photo-1600271886742-f049cd451bba?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8b3JhbmdlJTIwanVpY2V8ZW58MHx8MHx8fDA%3D",
    },
    {
      "productId": 1018,
      "category": {"cId": 2005, "categoryName": "Meat"},
      "brand": {"bId": 3005, "brandName": "Prime Cut"},
      "remark": {"rId": 4004, "remarkName": "Premium"},
      "productName": "Ground Beef",
      "description": "Lean ground beef",
      "quantity": "500",
      "quantity_unit": "g",
      "price": 5.99,
      "discount": 0.00,
      "ratings": 4.6,
      "available": true,
      "stockAmount": 30,
      "image":
          "https://hungryherd.ca/cdn/shop/products/ground_beef.jpg?v=1621390126",
    },
    {
      "productId": 1019,
      "category": {"cId": 2012, "categoryName": "Pasta & Rice"},
      "brand": {"bId": 3015, "brandName": "Al Dente"},
      "remark": {"rId": 4013, "remarkName": "Pantry Staple"},
      "productName": "Spaghetti",
      "description": "Durum wheat spaghetti",
      "quantity": "500",
      "quantity_unit": "g",
      "price": 1.49,
      "discount": 0.00,
      "ratings": 4.2,
      "available": true,
      "stockAmount": 120,
      "image":
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrXjohW4CcF-B-kkFPmk3meMDJRBauJ6BoAg&s",
    },
    {
      "productId": 1020,
      "category": {"cId": 2013, "categoryName": "Breakfast"},
      "brand": {"bId": 3016, "brandName": "MorningSun"},
      "remark": {"rId": 4001, "remarkName": "Best Selling"},
      "productName": "Corn Flakes",
      "description": "Classic corn flakes cereal",
      "quantity": "500",
      "quantity_unit": "g",
      "price": 2.99,
      "discount": 0.20,
      "ratings": 4.3,
      "available": true,
      "stockAmount": 80,
      "image":
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSkrHWqU_a1VumxqfE0a2nxFP03q-LSZ8Aqtw&s",
    },
    {
      "productId": 1021,
      "category": {"cId": 2002, "categoryName": "Vegetables"},
      "brand": {"bId": 3002, "brandName": "Green Harvest"},
      "remark": {"rId": 4002, "remarkName": "Organic"},
      "productName": "Spinach",
      "description": "Fresh organic spinach leaves",
      "quantity": "200",
      "quantity_unit": "g",
      "price": 2.29,
      "discount": 0.00,
      "ratings": 4.4,
      "available": true,
      "stockAmount": 45,
      "image":
          "https://www.shutterstock.com/image-photo/background-fresh-green-spinach-leaves-260nw-2491123299.jpg",
    },
    {
      "productId": 1022,
      "category": {"cId": 2007, "categoryName": "Snacks"},
      "brand": {"bId": 3017, "brandName": "Nutty"},
      "remark": {"rId": 4014, "remarkName": "Healthy"},
      "productName": "Almonds",
      "description": "Raw unsalted almonds",
      "quantity": "200",
      "quantity_unit": "g",
      "price": 4.99,
      "discount": 0.00,
      "ratings": 4.7,
      "available": true,
      "stockAmount": 60,
      "image":
          "https://www.halfnuts.net/cdn/shop/products/raw_15f1a7c9-c8fa-4da6-a744-c0acf64695f2.png?v=1547507240",
    },
    {
      "productId": 1023,
      "category": {"cId": 2003, "categoryName": "Dairy"},
      "brand": {"bId": 3003, "brandName": "MilkLife"},
      "remark": {"rId": 4006, "remarkName": "Essential"},
      "productName": "Greek Yogurt",
      "description": "Creamy Greek yogurt",
      "quantity": "500",
      "quantity_unit": "g",
      "price": 3.29,
      "discount": 0.00,
      "ratings": 4.5,
      "available": true,
      "stockAmount": 35,
      "image": "",
    },
    {
      "productId": 1024,
      "category": {"cId": 2014, "categoryName": "Condiments"},
      "brand": {"bId": 3018, "brandName": "FlavorMax"},
      "remark": {"rId": 4015, "remarkName": "Gluten Free"},
      "productName": "Tomato Ketchup",
      "description": "Classic tomato ketchup",
      "quantity": "500",
      "quantity_unit": "g",
      "price": 2.49,
      "discount": 0.00,
      "ratings": 4.6,
      "available": true,
      "stockAmount": 70,
      "image": "",
    },
    {
      "productId": 1025,
      "category": {"cId": 2008, "categoryName": "Frozen Foods"},
      "brand": {"bId": 3008, "brandName": "Frosty"},
      "remark": {"rId": 4008, "remarkName": "Easy Meal"},
      "productName": "French Fries",
      "description": "Crinkle cut french fries",
      "quantity": "1",
      "quantity_unit": "kg",
      "price": 2.99,
      "discount": 0.00,
      "ratings": 4.2,
      "available": true,
      "stockAmount": 50,
      "image": "",
    },
    {
      "productId": 1026,
      "category": {"cId": 2001, "categoryName": "Fruits"},
      "brand": {"bId": 3001, "brandName": "none"},
      "remark": {"rId": 4005, "remarkName": "Seasonal"},
      "productName": "Mango",
      "description": "Sweet ripe mango",
      "quantity": "1",
      "quantity_unit": "pc",
      "price": 1.99,
      "discount": 0.00,
      "ratings": 4.8,
      "available": true,
      "stockAmount": 40,
      "image": "",
    },
    {
      "productId": 1027,
      "category": {"cId": 2015, "categoryName": "Baking"},
      "brand": {"bId": 3019, "brandName": "Baker's Choice"},
      "remark": {"rId": 4013, "remarkName": "Pantry Staple"},
      "productName": "All-Purpose Flour",
      "description": "Premium wheat flour",
      "quantity": "1",
      "quantity_unit": "kg",
      "price": 1.79,
      "discount": 0.00,
      "ratings": 4.3,
      "available": true,
      "stockAmount": 90,
      "image": "",
    },
    {
      "productId": 1028,
      "category": {"cId": 2009, "categoryName": "Canned Goods"},
      "brand": {"bId": 3009, "brandName": "Pantry"},
      "remark": {"rId": 4009, "remarkName": "Long Shelf Life"},
      "productName": "Tuna in Water",
      "description": "Chunk light tuna",
      "quantity": "150",
      "quantity_unit": "g",
      "price": 1.69,
      "discount": 0.00,
      "ratings": 4.4,
      "available": true,
      "stockAmount": 65,
      "image": "",
    },
    {
      "productId": 1029,
      "category": {"cId": 2016, "categoryName": "Spices"},
      "brand": {"bId": 3020, "brandName": "SpiceWorld"},
      "remark": {"rId": 4016, "remarkName": "Gourmet"},
      "productName": "Black Pepper",
      "description": "Whole black peppercorns",
      "quantity": "50",
      "quantity_unit": "g",
      "price": 2.29,
      "discount": 0.00,
      "ratings": 4.7,
      "available": true,
      "stockAmount": 85,
      "image": "",
    },
    {
      "productId": 1030,
      "category": {"cId": 2006, "categoryName": "Beverages"},
      "brand": {"bId": 3021, "brandName": "BrewMaster"},
      "remark": {"rId": 4001, "remarkName": "Best Selling"},
      "productName": "Green Tea",
      "description": "Premium green tea bags",
      "quantity": "20",
      "quantity_unit": "bags",
      "price": 3.99,
      "discount": 0.00,
      "ratings": 4.6,
      "available": true,
      "stockAmount": 55,
      "image": "",
    },
    {
      "productId": 1031,
      "category": {"cId": 2002, "categoryName": "Vegetables"},
      "brand": {"bId": 3002, "brandName": "Green Harvest"},
      "remark": {"rId": 4002, "remarkName": "Organic"},
      "productName": "Bell Pepper",
      "description": "Mixed color bell peppers",
      "quantity": "3",
      "quantity_unit": "pcs",
      "price": 2.99,
      "discount": 0.00,
      "ratings": 4.5,
      "available": true,
      "stockAmount": 40,
      "image": "",
    },
    {
      "productId": 1032,
      "category": {"cId": 2004, "categoryName": "Bakery"},
      "brand": {"bId": 3004, "brandName": "Golden Grain"},
      "remark": {"rId": 4007, "remarkName": "Family Pack"},
      "productName": "Baguette",
      "description": "Fresh French baguette",
      "quantity": "1",
      "quantity_unit": "loaf",
      "price": 1.99,
      "discount": 0.00,
      "ratings": 4.4,
      "available": true,
      "stockAmount": 30,
      "image": "",
    },
    {
      "productId": 1033,
      "category": {"cId": 2003, "categoryName": "Dairy"},
      "brand": {"bId": 3022, "brandName": "ButterUp"},
      "remark": {"rId": 4006, "remarkName": "Essential"},
      "productName": "Unsalted Butter",
      "description": "Creamy unsalted butter",
      "quantity": "250",
      "quantity_unit": "g",
      "price": 3.79,
      "discount": 0.00,
      "ratings": 4.7,
      "available": true,
      "stockAmount": 45,
      "image": "",
    },
    {
      "productId": 1034,
      "category": {"cId": 2007, "categoryName": "Snacks"},
      "brand": {"bId": 3007, "brandName": "Crunchy"},
      "remark": {"rId": 4017, "remarkName": "Kids Favorite"},
      "productName": "Chocolate Cookies",
      "description": "Chocolate chip cookies",
      "quantity": "200",
      "quantity_unit": "g",
      "price": 2.29,
      "discount": 0.00,
      "ratings": 4.8,
      "available": true,
      "stockAmount": 70,
      "image": "",
    },
    {
      "productId": 1035,
      "category": {"cId": 2005, "categoryName": "Meat"},
      "brand": {"bId": 3005, "brandName": "Prime Cut"},
      "remark": {"rId": 4004, "remarkName": "Premium"},
      "productName": "Salmon Fillet",
      "description": "Fresh Atlantic salmon",
      "quantity": "1",
      "quantity_unit": "kg",
      "price": 12.99,
      "discount": 0.00,
      "ratings": 4.9,
      "available": true,
      "stockAmount": 20,
      "image":
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxNBewm_951keMLUxKLyDGYf-Z100qDwXzLg&s",
    },
    {
      "productId": 1036,
      "category": {"cId": 2001, "categoryName": "Fruits"},
      "brand": {"bId": 3001, "brandName": "none"},
      "remark": {"rId": 4005, "remarkName": "Seasonal"},
      "productName": "Pineapple",
      "description": "Sweet golden pineapple",
      "quantity": "1",
      "quantity_unit": "pc",
      "price": 3.49,
      "discount": 0.00,
      "ratings": 4.6,
      "available": true,
      "stockAmount": 25,
      "image": "",
    },
    {
      "productId": 1037,
      "category": {"cId": 2012, "categoryName": "Pasta & Rice"},
      "brand": {"bId": 3015, "brandName": "Al Dente"},
      "remark": {"rId": 4013, "remarkName": "Pantry Staple"},
      "productName": "Basmati Rice",
      "description": "Premium long grain rice",
      "quantity": "1",
      "quantity_unit": "kg",
      "price": 4.49,
      "discount": 0.00,
      "ratings": 4.5,
      "available": true,
      "stockAmount": 60,
      "image": "",
    },
    {
      "productId": 1038,
      "category": {"cId": 2017, "categoryName": "Pet Care"},
      "brand": {"bId": 3023, "brandName": "PetLove"},
      "remark": {"rId": 4018, "remarkName": "Vet Recommended"},
      "productName": "Dog Food",
      "description": "Complete nutrition for dogs",
      "quantity": "3",
      "quantity_unit": "kg",
      "price": 12.99,
      "discount": 0.00,
      "ratings": 4.7,
      "available": true,
      "stockAmount": 35,
      "image": "",
    },
    {
      "productId": 1039,
      "category": {"cId": 2010, "categoryName": "Personal Care"},
      "brand": {"bId": 3011, "brandName": "CleanLife"},
      "remark": {"rId": 4010, "remarkName": "Eco-Friendly"},
      "productName": "Shampoo",
      "description": "Natural coconut shampoo",
      "quantity": "400",
      "quantity_unit": "ml",
      "price": 5.49,
      "discount": 0.00,
      "ratings": 4.5,
      "available": true,
      "stockAmount": 50,
      "image": "",
    },
    {
      "productId": 1040,
      "category": {"cId": 2009, "categoryName": "Canned Goods"},
      "brand": {"bId": 3009, "brandName": "Pantry"},
      "remark": {"rId": 4009, "remarkName": "Long Shelf Life"},
      "productName": "Chickpeas",
      "description": "Cooked chickpeas in water",
      "quantity": "400",
      "quantity_unit": "g",
      "price": 1.29,
      "discount": 0.00,
      "ratings": 4.3,
      "available": true,
      "stockAmount": 80,
      "image": "",
    },
    {
      "productId": 1041,
      "category": {"cId": 2002, "categoryName": "Vegetables"},
      "brand": {"bId": 3002, "brandName": "Green Harvest"},
      "remark": {"rId": 4002, "remarkName": "Organic"},
      "productName": "Zucchini",
      "description": "Fresh organic zucchini",
      "quantity": "1",
      "quantity_unit": "kg",
      "price": 3.49,
      "discount": 0.00,
      "ratings": 4.4,
      "available": true,
      "stockAmount": 35,
      "image": "",
    },
    {
      "productId": 1042,
      "category": {"cId": 2006, "categoryName": "Beverages"},
      "brand": {"bId": 3024, "brandName": "CoffeeTime"},
      "remark": {"rId": 4001, "remarkName": "Best Selling"},
      "productName": "Ground Coffee",
      "description": "Arabica ground coffee",
      "quantity": "250",
      "quantity_unit": "g",
      "price": 4.99,
      "discount": 0.00,
      "ratings": 4.8,
      "available": true,
      "stockAmount": 45,
      "image": "",
    },
    {
      "productId": 1043,
      "category": {"cId": 2003, "categoryName": "Dairy"},
      "brand": {"bId": 3003, "brandName": "MilkLife"},
      "remark": {"rId": 4006, "remarkName": "Essential"},
      "productName": "Eggs",
      "description": "Free range eggs",
      "quantity": "12",
      "quantity_unit": "pcs",
      "price": 3.99,
      "discount": 0.00,
      "ratings": 4.6,
      "available": true,
      "stockAmount": 60,
      "image": "",
    },
    {
      "productId": 1044,
      "category": {"cId": 2018, "categoryName": "Baby Care"},
      "brand": {"bId": 3025, "brandName": "BabySoft"},
      "remark": {"rId": 4019, "remarkName": "Hypoallergenic"},
      "productName": "Baby Wipes",
      "description": "Gentle unscented baby wipes",
      "quantity": "80",
      "quantity_unit": "pcs",
      "price": 3.29,
      "discount": 0.00,
      "ratings": 4.7,
      "available": true,
      "stockAmount": 50,
      "image": "",
    },
    {
      "productId": 1045,
      "category": {"cId": 2007, "categoryName": "Snacks"},
      "brand": {"bId": 3017, "brandName": "Nutty"},
      "remark": {"rId": 4014, "remarkName": "Healthy"},
      "productName": "Trail Mix",
      "description": "Mixed nuts and dried fruits",
      "quantity": "300",
      "quantity_unit": "g",
      "price": 5.49,
      "discount": 0.00,
      "ratings": 4.5,
      "available": true,
      "stockAmount": 40,
      "image": "",
    },
    {
      "productId": 1046,
      "category": {"cId": 2004, "categoryName": "Bakery"},
      "brand": {"bId": 3013, "brandName": "SweetTreat"},
      "remark": {"rId": 4003, "remarkName": "New Arrival"},
      "productName": "Cinnamon Roll",
      "description": "Fresh baked cinnamon roll",
      "quantity": "1",
      "quantity_unit": "pc",
      "price": 2.49,
      "discount": 0.50,
      "ratings": 4.9,
      "available": true,
      "stockAmount": 20,
      "image": "",
    },
    {
      "productId": 1047,
      "category": {"cId": 2019, "categoryName": "Alcohol"},
      "brand": {"bId": 3026, "brandName": "Vineyard"},
      "remark": {"rId": 4020, "remarkName": "Aged"},
      "productName": "Red Wine",
      "description": "Premium Cabernet Sauvignon",
      "quantity": "1",
      "quantity_unit": "bottle",
      "price": 15.99,
      "discount": 0.00,
      "ratings": 4.8,
      "available": true,
      "stockAmount": 25,
      "image": "",
    },
    {
      "productId": 1048,
      "category": {"cId": 2008, "categoryName": "Frozen Foods"},
      "brand": {"bId": 3008, "brandName": "Frosty"},
      "remark": {"rId": 4008, "remarkName": "Easy Meal"},
      "productName": "Vegetable Pizza",
      "description": "Frozen vegetable pizza",
      "quantity": "1",
      "quantity_unit": "pc",
      "price": 4.99,
      "discount": 0.00,
      "ratings": 4.3,
      "available": true,
      "stockAmount": 30,
      "image": "",
    },
    {
      "productId": 1049,
      "category": {"cId": 2014, "categoryName": "Condiments"},
      "brand": {"bId": 3018, "brandName": "FlavorMax"},
      "remark": {"rId": 4015, "remarkName": "Gluten Free"},
      "productName": "Mayonnaise",
      "description": "Classic creamy mayonnaise",
      "quantity": "400",
      "quantity_unit": "g",
      "price": 2.99,
      "discount": 0.00,
      "ratings": 4.5,
      "available": true,
      "stockAmount": 55,
      "image": "",
    },
    {
      "productId": 1050,
      "category": {"cId": 2001, "categoryName": "Fruits"},
      "brand": {"bId": 3001, "brandName": "none"},
      "remark": {"rId": 4001, "remarkName": "Best Selling"},
      "productName": "Apple",
      "description": "Crisp red apples",
      "quantity": "1",
      "quantity_unit": "kg",
      "price": 2.99,
      "discount": 0.00,
      "ratings": 4.7,
      "available": true,
      "stockAmount": 80,
      "image": "",
    },
  ];
}
