// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXYEz7SFO2GE0LF2tU72_7Rr3Pa0UqYRc',
    appId: '1:139656798191:web:5439ab59990c2fb518201a',
    messagingSenderId: '139656798191',
    projectId: 'farmers-nest-de9c5',
    authDomain: 'farmers-nest-de9c5.firebaseapp.com',
    storageBucket: 'farmers-nest-de9c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGJi82IX4thH0yj3plGFQiwUDXkAO2Bok',
    appId: '1:139656798191:android:554a693df58405c518201a',
    messagingSenderId: '139656798191',
    projectId: 'farmers-nest-de9c5',
    storageBucket: 'farmers-nest-de9c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJJ3W1bTX-OGDowNcjK7TXLfn5y3NH-wg',
    appId: '1:139656798191:ios:30f82f9068251c1d18201a',
    messagingSenderId: '139656798191',
    projectId: 'farmers-nest-de9c5',
    storageBucket: 'farmers-nest-de9c5.firebasestorage.app',
    iosBundleId: 'com.example.farmersNest',
  );
}
